# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-09-12 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.CharField(default=False, max_length=32),
        ),
    ]
